version: '3.8'

services:
  web:
    build: .
    image: pratesk24/p2-backend-api:latest
    container_name: p2_backend_api_container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1